wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.49.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742581681.585157
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 63
      - 71
      - 83
      - 84
      - 98
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 63
      - 71
      - 83
      - 84
      - 98
      3:
      - 5
      - 7
      - 13
      - 19
      - 23
      4: 3.10.12
      5: 0.16.2
      6: 4.49.0
      8:
      - 5
      9:
        1: transformers_trainer
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
beta:
  desc: null
  value: 0.04
bf16:
  desc: null
  value: true
fp16:
  desc: null
  value: false
fsdp:
  desc: null
  value: []
seed:
  desc: null
  value: 42
tf32:
  desc: null
  value: null
debug:
  desc: null
  value: []
optim:
  desc: null
  value: adamw_torch
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
prefix:
  desc: null
  value: null
do_eval:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
do_train:
  desc: null
  value: false
head_dim:
  desc: null
  value: 128
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
mlp_bias:
  desc: null
  value: false
run_name:
  desc: null
  value: seed-llama-8b-GRPO-resq
use_ipex:
  desc: null
  value: false
use_vllm:
  desc: null
  value: false
adafactor:
  desc: null
  value: false
data_seed:
  desc: null
  value: null
deepspeed:
  desc: null
  value: /lid/home/saydalie/multimodal_cot/SEED/MultiModalLLM/configs/deepspeed/stage2_bf16.json
do_sample:
  desc: null
  value: false
hub_token:
  desc: null
  value: <HUB_TOKEN>
log_level:
  desc: null
  value: info
max_steps:
  desc: null
  value: -1
num_beams:
  desc: null
  value: 1
ray_scope:
  desc: null
  value: last
report_to:
  desc: null
  value:
  - wandb
typical_p:
  desc: null
  value: 1.0
use_cache:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.95
do_predict:
  desc: null
  value: false
eval_delay:
  desc: null
  value: 0
eval_steps:
  desc: null
  value: null
hidden_act:
  desc: null
  value: silu
is_decoder:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
max_length:
  desc: null
  value: 20
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: llama
optim_args:
  desc: null
  value: null
output_dir:
  desc: null
  value: /lid/home/saydalie/multimodal_cot/models/SEED_trained/seed-llama-8b-GRPO-resq
past_index:
  desc: null
  value: -1
rope_theta:
  desc: null
  value: 10000.0
save_steps:
  desc: null
  value: 0.05
vllm_dtype:
  desc: null
  value: auto
vocab_size:
  desc: null
  value: 40194
ddp_backend:
  desc: null
  value: null
ddp_timeout:
  desc: null
  value: 1800
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_v2: false
    xla_fsdp_grad_ckpt: false
hidden_size:
  desc: null
  value: 4096
label_names:
  desc: null
  value: null
logging_dir:
  desc: null
  value: /lid/home/saydalie/multimodal_cot/models/SEED_trained/seed-llama-8b-GRPO-resq/runs/Mar21_18-27-50_train-0-6
peft_config:
  desc: null
  value:
    default:
      task_type: CAUSAL_LM
      peft_type: LORA
      auto_mapping: null
      base_model_name_or_path: /lid/home/saydalie/multimodal_cot/SEED/checkpoints/seed-llama-8b-sft-comm
      revision: null
      inference_mode: false
      r: 16
      target_modules:
      - gate_proj
      - down_proj
      - q_proj
      - v_proj
      - k_proj
      - o_proj
      - up_proj
      exclude_modules: null
      lora_alpha: 32
      lora_dropout: 0.05
      fan_in_fan_out: false
      bias: none
      use_rslora: false
      modules_to_save:
      - embed_tokens
      - lm_head
      - input_layernorm
      - post_attention_layernorm
      - norm
      init_lora_weights: true
      layers_to_transform: null
      layers_pattern: null
      rank_pattern: {}
      alpha_pattern: {}
      megatron_config: null
      megatron_core: megatron.core
      trainable_token_indices: null
      loftq_config: {}
      eva_config: null
      corda_config: null
      use_dora: false
      layer_replication: null
      runtime_config:
        ephemeral_gpu_offload: false
      lora_bias: false
push_to_hub:
  desc: null
  value: false
return_dict:
  desc: null
  value: true
temperature:
  desc: null
  value: 0.9
torch_dtype:
  desc: null
  value: float32
torchdynamo:
  desc: null
  value: null
torchscript:
  desc: null
  value: false
vllm_device:
  desc: null
  value: auto
adam_epsilon:
  desc: null
  value: 1.0e-05
bos_token_id:
  desc: null
  value: 0
disable_tqdm:
  desc: null
  value: false
eos_token_id:
  desc: null
  value: 1
fp16_backend:
  desc: null
  value: auto
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
pad_token_id:
  desc: null
  value: -1
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
rms_norm_eps:
  desc: null
  value: 1.0e-06
rope_scaling:
  desc: null
  value: null
sep_token_id:
  desc: null
  value: null
use_bfloat16:
  desc: null
  value: false
warmup_ratio:
  desc: null
  value: 0.01
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.05
_name_or_path:
  desc: null
  value: /lid/home/saydalie/multimodal_cot/SEED/checkpoints/seed-llama-8b-sft-comm
architectures:
  desc: null
  value:
  - LlamaForCausalLM
bad_words_ids:
  desc: null
  value: null
eval_on_start:
  desc: null
  value: false
eval_strategy:
  desc: null
  value: 'no'
jit_mode_eval:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 5.0e-07
logging_steps:
  desc: null
  value: 0.01
max_grad_norm:
  desc: null
  value: 1.0
mp_parameters:
  desc: null
  value: ''
output_scores:
  desc: null
  value: false
save_strategy:
  desc: null
  value: steps
split_batches:
  desc: null
  value: null
torch_compile:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: null
attention_bias:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
length_penalty:
  desc: null
  value: 1.0
pretraining_tp:
  desc: null
  value: 1
reward_weights:
  desc: null
  value: null
sync_ref_model:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
finetuning_task:
  desc: null
  value: null
group_by_length:
  desc: null
  value: false
hub_always_push:
  desc: null
  value: false
log_completions:
  desc: null
  value: false
num_beam_groups:
  desc: null
  value: 1
num_generations:
  desc: null
  value: 8
save_only_model:
  desc: null
  value: false
suppress_tokens:
  desc: null
  value: null
tokenizer_class:
  desc: null
  value: null
dispatch_batches:
  desc: null
  value: null
full_determinism:
  desc: null
  value: false
hub_private_repo:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
log_on_each_node:
  desc: null
  value: true
logging_strategy:
  desc: null
  value: steps
num_train_epochs:
  desc: null
  value: 10
save_safetensors:
  desc: null
  value: true
save_total_limit:
  desc: null
  value: null
use_liger_kernel:
  desc: null
  value: false
attention_dropout:
  desc: null
  value: 0.0
ddp_bucket_cap_mb:
  desc: null
  value: null
diversity_penalty:
  desc: null
  value: 0.0
greater_is_better:
  desc: null
  value: null
initializer_range:
  desc: null
  value: 0.02
intermediate_size:
  desc: null
  value: 11008
log_level_replica:
  desc: null
  value: warning
lr_scheduler_type:
  desc: null
  value: cosine
max_prompt_length:
  desc: null
  value: 512
model_init_kwargs:
  desc: null
  value: null
num_hidden_layers:
  desc: null
  value: 32
output_attentions:
  desc: null
  value: false
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
save_on_each_node:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
accelerator_config:
  desc: null
  value:
    split_batches: false
    dispatch_batches: null
    even_batches: true
    use_seedable_sampler: true
    non_blocking: false
    gradient_accumulation_kwargs: null
batch_eval_metrics:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
logging_first_step:
  desc: null
  value: false
repetition_penalty:
  desc: null
  value: 1.0
torch_compile_mode:
  desc: null
  value: null
vllm_max_model_len:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fsdp_min_num_params:
  desc: null
  value: 0
include_for_metrics:
  desc: null
  value: []
lr_scheduler_kwargs:
  desc: null
  value: {}
max_sequence_length:
  desc: null
  value: 2048
neftune_noise_alpha:
  desc: null
  value: null
num_attention_heads:
  desc: null
  value: 32
num_key_value_heads:
  desc: null
  value: 32
skip_memory_metrics:
  desc: null
  value: true
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: false
auto_find_batch_size:
  desc: null
  value: false
dataloader_drop_last:
  desc: null
  value: false
model/num_parameters:
  desc: null
  value: 7175053312
no_repeat_ngram_size:
  desc: null
  value: 0
num_return_sequences:
  desc: null
  value: 1
optim_target_modules:
  desc: null
  value: null
output_hidden_states:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: false
prediction_loss_only:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: null
ref_model_sync_steps:
  desc: null
  value: 64
task_specific_params:
  desc: null
  value: null
transformers_version:
  desc: null
  value: 4.49.0
begin_suppress_tokens:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
ddp_broadcast_buffers:
  desc: null
  value: null
max_completion_length:
  desc: null
  value: 1024
metric_for_best_model:
  desc: null
  value: null
ref_model_mixup_alpha:
  desc: null
  value: 0.9
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 8
decoder_start_token_id:
  desc: null
  value: null
eval_do_concat_batches:
  desc: null
  value: true
eval_use_gather_object:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
label_smoothing_factor:
  desc: null
  value: 0.0
load_best_model_at_end:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: 'no'
resume_from_checkpoint:
  desc: null
  value: null
chunk_size_feed_forward:
  desc: null
  value: 0
eval_accumulation_steps:
  desc: null
  value: null
max_position_embeddings:
  desc: null
  value: 2048
per_gpu_eval_batch_size:
  desc: null
  value: null
return_dict_in_generate:
  desc: null
  value: false
torch_empty_cache_steps:
  desc: null
  value: null
per_gpu_train_batch_size:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
ds3_gather_for_generation:
  desc: null
  value: true
include_tokens_per_second:
  desc: null
  value: false
dataloader_prefetch_factor:
  desc: null
  value: null
ddp_find_unused_parameters:
  desc: null
  value: null
include_inputs_for_metrics:
  desc: null
  value: false
per_device_eval_batch_size:
  desc: null
  value: 8
use_legacy_prediction_loop:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 4
per_device_train_batch_size:
  desc: null
  value: 16
vllm_gpu_memory_utilization:
  desc: null
  value: 0.9
_attn_implementation_autoset:
  desc: null
  value: true
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
average_tokens_across_devices:
  desc: null
  value: false
dataloader_persistent_workers:
  desc: null
  value: false
gradient_checkpointing_kwargs:
  desc: null
  value: null
include_num_input_tokens_seen:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
restore_callback_states_from_checkpoint:
  desc: null
  value: false
